#!/bin/bash
# usage examples:
# qrauth
# qrauth && sudo -i

#set +e
#TTY=/dev/stdout
TTY=/dev/stderr
NUL=/dev/null
HTTPPORT=8080
QRAUTHFN="qrauth.txt"
PTPPATH="/store_00010001/Pictures"

SELFPID=$$
SESSPUBKEY="SESSPUBKEY"
cd /tmp


KEYRING_ID=`keyctl search @u user "$SESSPUBKEY" 2>$NUL`
if [ ! -z "$KEYRING_ID" ]; then
  keyctl unlink $KEYRING_ID >$TTY
fi

KEYRING_ID=`age-keygen 2>$NUL | grep AGE-SECRET-KEY | keyctl padd user "$SESSPUBKEY" @u`
PUBKEY=`keyctl pipe $KEYRING_ID | age-keygen -y`

USBIFCIP="0.0.0.0"
for interface in /sys/class/net/*; do
  ifc=$(readlink "$interface")
  if [[ "$ifc" == */usb* ]] >$TTY; then
    ifcn=${interface#/sys/class/net/}
    USBIFCIP=$(ifconfig $ifcn | grep netmask | awk '{print $2}' | tr -d '\n')
    echo "">$TTY
    echo "USB network interface IP: $USBIFCIP">$TTY
  fi
done

HOSTNAME=$(hostname)
WHOAMI=$(whoami)
if [ -z "$HOSTNAME" ]; then
  HOSTNAME="HOSTNAME"
fi

PUBKEY=111/$HOSTNAME/qrauth/$WHOAMI/$USBIFCIP/$PUBKEY
ISPTPMODE=0
if [ -e /usr/bin/gphoto2 ]; then
  echo -n "$PUBKEY">$QRAUTHFN
  gphoto2 -q -f $PTPPATH -d $QRAUTHFN 2>$NUL 1>$NUL
  gphoto2 -q --force-overwrite -f $PTPPATH -u $QRAUTHFN 2>$NUL 1>$NUL
  if [ $? -eq 0 ]; then
    ISPTPMODE=${#PUBKEY}
    echo "USB PTP Mode is active! Now you could enable USB mode switcher in PWA UI">$TTY
  fi
fi
qrencode -t ANSI256UTF8 "$PUBKEY">$TTY
echo "and now 62 countdown seconds of waiting the passkey via QR codes (or press Ctrl+C)...">$TTY


QRdataComplete() {
  tmpfn=$(mktemp)
  echo "$1" | base64 -d >$tmpfn
  keyctl pipe $KEYRING_ID | age -d -i - $tmpfn | keyctl pupdate $KEYRING_ID  # workaround: because breaks from this WHILE does kill all VARS
  rm $tmpfn
  ZBARPID=`ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}'`
  kill -9 $ZBARPID >$NUL
  return 0
}

zbarfifo=/tmp/zbarcam.fifo  #case for no webcam
tmpfifo=/tmp/qrauth.nc.fifo
rm -f $tmpfifo >$NUL
mkfifo $tmpfifo || exit 1
(
cat $tmpfifo | nc -l -p $HTTPPORT | grep --line-buffered GET | \
while read -r GET >$NUL; do
  data=${GET##*&}
  QRDATA=${data% *}
  echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 2\r\nAccess-Control-Allow-Origin: *\r\n\r\nOK" >$tmpfifo
  QRdataComplete $QRDATA
  break
done
)&
FIFOPID=$!

BASE62="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
TIMEOUT=62
(while [ -e $tmpfifo -a $TIMEOUT -gt 0 ]>$NUL; do
  sleep 1 >$NUL
  echo "$BASE62" | cut -zc$TIMEOUT >$TTY
  TIMEOUT=$((TIMEOUT-1))
  if [ $ISPTPMODE -ne 0 ]; then
    QRDATA=`gphoto2 -q --force-overwrite -f $PTPPATH -p $QRAUTHFN --stdout 2>$TTY`
    DATASIZE=${#QRDATA}
    if [ ! -z "$QRDATA" -a $DATASIZE -gt $ISPTPMODE ]; then
      QRdataComplete $QRDATA
      gphoto2 -q -f $PTPPATH -d $QRAUTHFN 2>$NUL 1>$NUL
      break
    fi
  fi
 done
 ISKEYID=`keyctl show @u | grep $KEYRING_ID  2>$NUL`
 if [ ! -z "$ISKEYID" ]; then
   keyctl unlink $KEYRING_ID >$NUL
 fi
 ZBARPID=`ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}'`
 if [ ! -z "$ZBARPID" ]; then
   kill -9 $ZBARPID >$NUL
 fi
)&
TIMEOUTPID=$!


terminate() {
  echo "terminate : $1 ">$TTY
  if [ -z "$1" ]; then
    ZBARPID=`ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}'`
    if [ ! -z "$ZBARPID" ]; then
      kill -9 $ZBARPID >$NUL
    fi
    sleep 0.1
  fi

  NCPID=`ps -Af | egrep "nc -l -p $HTTPPORT" | grep -v grep | awk '{print $2}'`
  if [ ! -z "$NCPID" ]; then
    kill -9 $NCPID >$NUL
    kill -9 $FIFOPID 2>$NUL 1>$NUL
  fi
  sleep 0.1

  FIFOPID=`ps -Af | grep $tmpfifo | grep -v grep | awk '{print $2}'`
  if [ ! -z "$FIFOPID" ]; then
    echo ".">$tmpfifo
#    kill -9 $FIFOPID 2>$NUL 1>$NUL
  fi
  rm -f $tmpfifo >$NUL
  rm -f $zbarfifo >$NUL

  ISTOPID=`ps -A | grep $TIMEOUTPID`
  if [ ! -z "$ISTOPID" ]; then
    kill -9 $TIMEOUTPID >$NUL
  fi

  keyctl unlink $KEYRING_ID >$NUL
  echo "">$TTY

  exit 0
}
trap terminate INT TERM

ISVIDEODEV=`ls /dev/video* 2>$NUL`
if [ -z "$ISVIDEODEV" ]; then
  if [ "$USBIFCIP" == "0.0.0.0" ]; then
    echo "No webcam found. Please enable USB modem on opened PWA device and start this again..." >$TTY
    sleep 1
    terminate
    exit 1
  fi
  echo "### No camera found! USB modem only way..." >$TTY
  test -e $zbarfifo || mkfifo $zbarfifo >$NUL
  cat $zbarfifo >$NUL
else
LEN=0
CNTR=""
zbarcam -q --nodisplay --nodbus --raw -Sdisable -Sqrcode.enable | \
while read -r QRCHUNK >$NUL; do
  NDGTS=`echo $QRCHUNK | cut -c 1`
  NCHUNKS=`echo $QRCHUNK | cut -c 2-$((NDGTS+1))`
  ICHUNK=`echo $QRCHUNK | cut -c $((NDGTS+2))-$((NDGTS*2+1))`
  echo " ">$TTY
  echo -n "{$ICHUNK/$NCHUNKS: ">$TTY
  ICHUNK=$(echo "obase=10; ibase=10; ${ICHUNK}" | bc)
  QRCHUNK=`echo "$QRCHUNK" | cut -c $((NDGTS*2+2))-`
  f=$(echo "$BASE62" | cut -c$ICHUNK)
  if echo "$CNTR" | grep -q $f; then
    echo -n "$LEN} # ">$TTY
  else
    CNTR=$CNTR$f
    VARCHUNK="QRCHUNK$ICHUNK"
    eval "$VARCHUNK=\"$QRCHUNK\""
    LEN=$((LEN+1))
    echo -n "$LEN} ">$TTY
  fi
  if [ $LEN -eq $NCHUNKS ]>$NUL; then
    QRDATA=""
    while [ $LEN -gt 0 ]; do
      VARCHUNK="QRCHUNK$LEN"
      eval "VAR=\$${VARCHUNK}"
      QRDATA=$VAR$QRDATA
      LEN=$((LEN-1))
    done

    QRdataComplete $QRDATA
    break
  fi
done
fi
sleep 0.1

ISKEYID=`keyctl show @u | grep $KEYRING_ID  2>$NUL`
if [ ! -z "$ISKEYID" ]; then
  PASSKEY=`keyctl pipe $KEYRING_ID`
  NL="
"
  CURRPASS=${PASSKEY%$NL*}
  NEWPASS=${PASSKEY##*$NL}
  echo -n "$CURRPASS" | sudo -S -v 2>$NUL 1>$NUL
  if [ "$?" -ne 0 ]; then
  echo "">$TTY
  echo "### !!! The received password is not valid, try again !!! ###" >$TTY
  else
    if [ "$CURRPASS" != "$NEWPASS" ]; then
      echo "$WHOAMI:$NEWPASS" | sudo chpasswd >$TTY
      echo "New password for $WHOAMI is applied" >$TTY
    fi
    echo "">$TTY
    echo "Now may execute \"sudo -i\" to get the root... (15sec)" >$TTY
  fi
  keyctl unlink $KEYRING_ID >$NUL
fi

terminate "1" 2>$NUL 1>$NUL

exit 0
